#RELACIONAMENTOS ENTRE A TABELA SALA E A TABELA ESPECIALIDADE

ALTER TABLE TBL_SALA ADD CONSTRAINT FK_ESPECIALIDADE_SALA
FOREIGN KEY (ID_ESPECIALIDADE)
REFERENCES TBL_ESPECIALIDADE(ID);

ALTER TABLE TBL_MEDICO ADD CONSTRAINT FK_ESPECIALIDADE_MEDICO
FOREIGN KEY(ID_ESPECIALIDADE)
REFERENCES TBL_ESPECIALIDADE(ID);

ALTER TABLE TBL_AGENDA ADD CONSTRAINT FK_MEDICO_AGENDA
FOREIGN KEY (ID_MEDICO) 
REFERENCES TBL_MEDICO(ID);

ALTER TABLE TBL_AGENDA ADD CONSTRAINT FK_PACIENTE_CIRURGIA
FOREIGN KEY (ID_PACIENTE)
REFERENCES TBL_PACIENTE(ID_PACIENTE);

ALTER TABLE TBL_AGENDA ADD CONSTRAINT FK_SALA_CIRURGIA
FOREIGN KEY (ID_SALA)
REFERENCES TBL_SALA(ID)

ALTER TABLE TBL_INSUMOS ADD CONSTRAINT FK_PACIENTE_INSUMO
FOREIGN KEY (ID_PACIENTE)
REFERENCES TBL_PACIENTE(ID_PACIENTE);