#RELACIONAMENTOS ENTRE A TABELA SALA E A TABELA ESPECIALIDADE

ALTER TABLE TBL_SALA ADD CONSTRAINT FK_ESPECIALIDADE 
FOREIGN KEY (ID_ESPECIALIDADE)
REFERENCES TBL_ESPECIALIDADE(ID);

#Eu acabei não executando o comando, pois ja fiz na tabela sem querer querendo ://////
