#GAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAYGAY


#CRIAÇÃO DO DELIMITADOR DE INICIO DA TRIGGER
DELIMITER $

CREATE TRIGGER TRG_DELETE_PACIENTE BEFORE DELETE ON TBL_PACIENTE

for each row #PARA CADA LINHA QUE SOFRE A AÇÃO DE DELETE
BEGIN
INSERT INTO TBL_PACIENTE_BKP
SET
ID_PACIENTE = OLD.ID_PACIENTE,
NOME_PACIENTE = OLD.NOME_PACIENTE,
CELULAR_PACIENTE = OLD.CELULAR_PACIENTE,
EMAIL_PACIENTE = OLD.EMAIL_PACIENTE,
NOME_RESPONSAVEL = OLD.NOME_RESPONSAVEL,
TELEFONE_RESPONSAVEL = OLD.TELEFONE_RESPONSAVEL;



END;